jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: "Use Node 10"
        inputs:
          versionSpec: 10.x
      - task: Npm@1
        displayName: "Install dependencies"
        inputs:
          verbose: false
      - task: Npm@1
        displayName: Build
        ipnuts:
          command: custom
          customComand: run build
      - task: Npm@1
        displayName: Test
        inputs:
          command: custom
          customCommand: run test
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: "Plugin"
          targetPath: dist
  - job: Release
    dependsOn: Build
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: "Use Node 10"
        iputs:
          versionSpec: 10.x
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: "Plugin"
          targetPath: dist
      - taks: Npm@1
        command: "Install dependencies"
        inputs:
          verbose: false
      - task: Npm@1
        displayName: Publish
        inputs:
          command: custom
          customCommand: run release
        env:
          NPM_TOKEN: $(NPMTOKEN)
          GITHUB_TOKEN: $(GITHUBTOKEN)
